apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: {{ include "patchmon.fullname" . }}-server
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "patchmon.fullname" . }}-server
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "patchmon.fullname" . }}-server
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "patchmon.fullname" . }}-server
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "patchmon.fullname" . }}-server
  apiGroup: rbac.authorization.k8s.io
