{{- range $name, $cfg := .Values.persistence }}
{{- if and $cfg.enabled (not $cfg.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless.fullname" $ }}-{{ $name }}
  labels:
    {{- include "paperless.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  accessModes:
    {{- range $cfg.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if $cfg.storageClass }}
  storageClassName: {{ $cfg.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $cfg.size }}
{{- end }}
{{- end }}
