apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-secret
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
  # PostgreSQL password
  {{- if .Values.postgresql.existingSecret }}
  # Password is in existing secret, not duplicated here
  {{- else }}
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
  {{- end }}
  
  # Redis password
  {{- if .Values.redis.existingSecret }}
  # Password is in existing secret, not duplicated here
  {{- else }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
  
  # Secret key for Django
  secret-key: {{ (randAlphaNum 50) | b64enc | quote }}
  
  # Mail password
  {{- if and .Values.config.paperless_mailhost .Values.config.paperless_mailpassword }}
  mail-password: {{ .Values.config.paperless_mailpassword | b64enc | quote }}
  {{- end }}
