apiVersion: v1
kind: Service
metadata:
  name: {{ include "silo-server.fullname" . }}
  labels:
    {{- include "silo-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.ui.port }}
      targetPort: ui
      protocol: TCP
      name: ui
    - port: {{ .Values.service.ports.jellyfin.port }}
      targetPort: jellyfin
      protocol: TCP
      name: jellyfin
  selector:
    {{- include "silo-server.selectorLabels" . | nindent 4 }}
