apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-notes-sync.fullname" . }}-config
  labels:
    {{- include "simple-notes-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |
    address: {{ .Values.config.address | quote }}
    port: {{ .Values.config.port }}
    directory: {{ .Values.config.directory | quote }}
    permissions: {{ .Values.config.permissions | quote }}
    debug: {{ .Values.config.debug }}

    log:
      format: console
      colors: false
      outputs:
        - stderr

    users:
      - username: {{ .Values.auth.username | quote }}
        password: {{ .Values.auth.password | quote }}
        permissions: CRUD
